security:
  jwt:
    secret-key: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"
    expiration-time: 8000000

currency:
  server:
    api:
      url: "http://api.exchangeratesapi.io/v1/latest"
      key: "67ce30f2153132bb71ccc5c6d89fe9aa"

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
  cors:
    front-end:
      url: ${FRONT_END_URL}

spring:
  jackson:
    time-zone: America/Sao_Paulo
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      properties:
        hibernate:
          globally_quoted_identifiers_skip_column_definitions: true
          globally_quoted_identifiers: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  url: ${DATABASE_URL}
  baseline-on-migrate: true
  enabled: true
  validate-on-migrate: true
  locations:
    - classpath:db/migration/common

