server:
  port: 9439

spring:
  jackson:
      time-zone: America/Sao_Paulo
  datasource:
      url: jdbc:h2:mem:bancotest;MODE=PostgreSQL
      username: admin
      password: admin
      driverClassName: org.h2.Driver
  h2:
     console:
        path: /h2-console
        enabled: true
        settings.web-allow-others: true
  jpa:
     hibernate.ddl-auto: update
flyway:
    url: jdbc:h2:mem:bancotest
    baseline-on-migrate: true
    enabled: true
    validate-on-migrate: true
    locations:
      - classpath:db/migration/common
      - classpath:db/migration/test
