server:
  servlet:
    context-path: /api
  port: 9439
  cors:
    front-end:
      url: "http://localhost:5173/"

security:
  jwt:
    secret-key: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"
    expiration-time: 8000000

currency:
   server:
       api:
          url: "http://api.exchangeratesapi.io/v1/latest"
          key: "67ce30f2153132bb71ccc5c6d89fe9aa"

spring:
  jackson:
      time-zone: America/Sao_Paulo
  datasource:
      url: jdbc:h2:mem:bancotest;MODE=PostgreSQL;
      username: admin
      password: admin
      driverClassName: org.h2.Driver
  h2:
     console:
        path: /h2-console
        enabled: true
        settings.web-allow-others: true
  jpa:
     show-sql: true
     properties:
       hibernate:
         globally_quoted_identifiers_skip_column_definitions: false
         globally_quoted_identifiers: false
     hibernate:
       naming:
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
       ddl-auto: validate
flyway:
    url: jdbc:h2:mem:bancotest
    baseline-on-migrate: true
    enabled: true
    validate-on-migrate: true
    locations:
      - classpath:db/migration/common
      - classpath:db/migration/test
