server:
  servlet:
    context-path: /api
  port: 9439

security:
  jwt:
    secret-key: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"
    expiration-time: 8000000

spring:
  jackson:
      time-zone: America/Sao_Paulo
  datasource:
      url: jdbc:h2:mem:bancotest;MODE=PostgreSQL;
      username: admin
      password: admin
      driverClassName: org.h2.Driver
  h2:
     console:
        path: /h2-console
        enabled: true
        settings.web-allow-others: true
  jpa:
     hibernate.ddl-auto: update
flyway:
    url: jdbc:h2:mem:bancotest
    baseline-on-migrate: true
    enabled: true
    validate-on-migrate: true
    locations:
      - classpath:db/migration/common
      - classpath:db/migration/test
