server:
  port: ${PORT:8080}
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: coinconverter

flyway:
  url: ${DATABASE_URL}
  schemas: coinconverter
  baseline-on-migrate: true
  enabled: true
  validate-on-migrate: true
  locations:
    - classpath:db/migration/common