CREATE TABLE "USERS_HIST_CURRCY_CONVRT" (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL,
    operation_date_time TIMESTAMP DEFAULT NULL,
    CONSTRAINT fk_user_hist_currcy_id FOREIGN KEY(user_id) REFERENCES USERS(id)
)