name: Build and Deploy to Heroku

on:
  push:
    branches: [ "develop" ]

env:
  JAVA_VERSION: '17'
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
  HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      build-success: ${{ steps.set-output.outputs.build-success }}
      artifact-name: ${{ steps.set-output.outputs.artifact-name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        run: |
          ./gradlew build --no-daemon
          ls -l build/libs/

      - name: Get JAR filename
        id: jar-name
        run: |
          JAR_FILE=$(ls build/libs/*.jar | head -n 1)
          echo "JAR_FILE=${JAR_FILE}" >> $GITHUB_OUTPUT
          echo "Found JAR file: ${JAR_FILE}"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: ${{ steps.jar-name.outputs.JAR_FILE }}
          retention-days: 1

      - name: Set output variables
        id: set-output
        run: |
          echo "build-success=true" >> $GITHUB_OUTPUT
          echo "artifact-name=spring-boot-app" >> $GITHUB_OUTPUT