name: Build and Deploy to Heroku

on:
  push:
    branches: [ "develop" ]

env:
  JAVA_VERSION: '17'
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
  HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        run: |
          ./gradlew build --no-daemon
          ls -l build/libs/

      - name: Get JAR filename
        id: jar-name
        run: |
          JAR_FILE=$(ls build/libs/*.jar | head -n 1)
          echo "JAR_FILE=${JAR_FILE}" >> $GITHUB_OUTPUT
          echo "Found JAR file: ${JAR_FILE}"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: ${{ steps.jar-name.outputs.JAR_FILE }}
          retention-days: 1

      - name: Set output variables
        id: set-output
        run: |
          echo "build-success=true" >> $GITHUB_OUTPUT
          echo "artifact-name=spring-boot-app" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    if: needs.build.outputs.build-success == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact-name }}

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ env.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_email: ${{ env.HEROKU_EMAIL }}
          usedocker: false
          branch: "main"
          buildpack: "heroku/java"
          appdir: "./"
          healthcheck: "https://${{ env.HEROKU_APP_NAME }}.herokuapp.com/actuator/health"
          rollbackonhealthcheckfailed: true
          delay: 10