name: CI/CD para o Back-end - Jaya Coin Converter

on:
  push:
    branches:
      - develop

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
             path: ~/.gradle/caches
             key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
             restore-keys: gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Compile and build
        run: ./gradlew build -x test
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: backend-jaya-coin-converter
        run: |
            echo "Logging in to Heroku..."
            heroku auth:whoami || echo "${HEROKU_API_KEY}" | heroku login
            echo "Deploying to Heroku app: ${HEROKU_APP_NAME}" 
            git remote add heroku https://:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git || git remote set-url heroku https://:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git
            git config --global user.email "github-actions@users.noreply.github.com"
            git config --global user.name "GitHub Actions"
            git checkout main || git checkout -b main
            git add dist -f
            git commit -m "Deploy built assets" || echo "No changes to commit"
            git push heroku main --force